src/services/resultsPanelProvider.ts
test/suite/panels.test.ts

- block the user from drop columns from results table

KXI-31286 - It's easy to accidentally drop columns from the KDB Results view

---

.github/workflows/ci.yml
.github/workflows/prod_release.yml
.github/workflows/release.yml

KXI-33201: Change Sonarqube quality gate

---

syntaxes/q.tmLanguage.json

fixes KXI-28503

---

syntaxes/q.tmLanguage.json

added @overview tag to qdoc highlighting

---

.vscode/settings.json
sonar-project.properties
src/models/dataSource.ts
src/webview/components/kdbDataSourceView.ts
test/fixtures/index.ts
test/fixtures/webview.ts
test/suite/webview.test.ts
test/tsconfig.json
tsconfig.json

- Fix for KXI-33307
- Foundation for further webview tests

Webview Tests

---

language-configuration.json
src/commands/dataSourceCommand.ts
src/panels/datasource.ts
syntaxes/q.tmLanguage.json

- Fixes KXI-33843 (datasource rename issue)
- Updated symbol pattern
- Updated word pattern to include symbol

fixes KXI-33843

---

package.json
sonar-project.properties
src/commands/dataSourceCommand.ts
src/commands/serverCommand.ts
src/extension.ts
src/models/execution.ts
src/models/queryHistory.ts
src/utils/executionConsole.ts
test/suite/commands.test.ts

-‘Execute Current Selection’ and ‘Execute Entire File’ for python files

KXI-29938 - Scratchpad - support execution of Python code from vscode

---

src/commands/dataSourceCommand.ts

KXI-33842 - Data Sources > QSQL not working

---

src/commands/serverCommand.ts

- Update wording when executing scratchpad queries

KXI-33845 Wording around scratchpads is confusing

---

src/commands/dataSourceCommand.ts

focus in results view when execute ds

---

CHANGELOG.md
package-lock.json
package.json

v1.2.1 Release

---

.vscode/settings.json
package-lock.json
package.json
test/runTest.ts

- Update `@vscode/test-electron` to 2.3.8 (bug is fixed upstream)

fix for Mac OS testing

---

.github/workflows/prod_release.yml
.github/workflows/release.yml

- Set retention time for vsix to 1 day

KXI-35517: Set retention time for vsix to 1 day

---

package-lock.json
package.json

Fix snyk report
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6124857

fix SNYK-JS-AXIOS-6124857

---

src/commands/serverCommand.ts
src/models/connection.ts
src/utils/execution.ts
test/suite/utils.test.ts

- added workaround to node-q
- get string as results for node-q execution, and handle it to transform into objects
- add tests

KXI-33265 - Fix Results tab for local connections

---

server/src/linter/assign.ts
server/src/linter/index.ts
server/src/linter/limit.ts
server/src/linter/other.ts
server/src/linter/rules.ts
test/suite/linter.test.ts

- Added following linter rules:
DECLARED_AFTER_USE
INVALID_ESCAPE
FIXED_SEED
TOO_MANY_ARGUMENTS

KXI-33804: Linting Phase 2

---

src/models/connection.ts
src/models/serverObject.ts
test/suite/models.test.ts

- fix to include all variable types

KXI-35806 Tree only lists longs

---

src/models/connection.ts

Solved the bug related to execution of local q

KXI-35931 - Fix issue with execute local queries

---

src/extension.ts
src/models/connection.ts

- Fix extension infinite loop when string queries are forbidden in q server
- Fix extension not activating with invalid settings.json

KXI-36135: q server where string queries are forbidden, KXI-35805: Invalid settings.json

---

src/ipc/cClasses.ts
src/models/connection.ts
src/services/resultsPanelProvider.ts
src/utils/execution.ts
src/utils/queryUtils.ts
src/webview/styles/resultsPanel.css
test/suite/commands.test.ts
test/suite/panels.test.ts
test/suite/utils.test.ts

- Fix results
- Add Index column, to be like in Insights Enterprise
- Add tooltip with QTypes to the column header(if the header has a type)

KXI-35687 Fix results tabs for insights

---

syntaxes/q.tmLanguage.json

KXI-36191: qdoc highlighting

---

package-lock.json
package.json
src/extensionVariables.ts
src/services/kdbInsights/codeFlowLogin.ts
test/suite/services.test.ts

- Randomize Insgihts connection port.
- Decrease login timeout from 5 mins to 3 mins.

KXI-36281: Fix for address in use

---

CHANGELOG.md

Add details to the enhancement and fix section of the 1.3 release

---

.github/workflows/app-sec-template.yml

KXI-36470: Fix typo in monitor job

---

.github/workflows/app-sec-template.yml

KXI-36470b: Fix Typo

---

.github/workflows/app-sec-template.yml

KXI-36470c: Check the correct value for ref_name

---

README.md
src/commands/dataSourceCommand.ts
src/commands/serverCommand.ts
src/extension.ts
src/models/queryHistory.ts
src/services/queryHistoryProvider.ts
src/utils/executionConsole.ts
src/utils/queryUtils.ts
test/suite/commands.test.ts
test/suite/services.test.ts
test/suite/utils.test.ts

- KXI-36321: add shortcuts for mac on docs
- KXI-36352: add duration in ms for query for local calls in query history(bug was lagging, but with the history can see that is less than 1sec)
- KXI-36554: New Feature: Query history for DS
- Refactored the entire query-history and rerun query methods

KXI-36321, KXI-36352, KXI-36554 bug fixes

---

src/commands/serverCommand.ts
src/utils/executionConsole.ts

- fix for "Nothing happens if you try running code with no connection open"

KXI-36322 - Nothing happens if you try running code with no connection open

---

.github/workflows/main.yml
.github/workflows/prod_release.yml
.github/workflows/release.yml

- Skip app-sec if PR from fork
- Skip ci if changes to md files
- update node version

KXI-36485: Adjustments to CI

---

src/commands/serverCommand.ts
src/utils/executionConsole.ts
test/suite/utils.test.ts

- KXI-36762 - fix bug add tests

KXI-36762 - "No results found." returned when evaluating function assignments

---

src/extensionVariables.ts
src/services/kdbTreeProvider.ts
src/utils/core.ts
src/validators/kdbValidator.ts
test/suite/utils.test.ts
test/suite/validators.test.ts

KXI-36572 - Connections should not be able to have the same name

---

src/commands/dataSourceCommand.ts
src/commands/serverCommand.ts

KXI-37193 - Add additional telemetry

---

src/commands/dataSourceCommand.ts
src/models/dataSource.ts
src/webview/components/kdbDataSourceView.ts
test/suite/commands.test.ts
test/suite/webview.test.ts

- remove slice time fields from temporality

KXI-37736 - GetDataAPI form changes: temporality/slice/fill inputs

---

src/validators/kdbValidator.ts
test/suite/commands.test.ts
test/suite/validators.test.ts

- Increased server input string limit to 2048 chars.

KXI-37861: Support longer strings for server config

---

README.md

- added changes requested in the ticket

KXI-37739 change README

---

CHANGELOG.md

Update CHANGELOG.md for 1.4

---

.github/workflows/prod_release.yml

Fix Typo in prod release

---

src/services/kdbInsights/codeFlowLogin.ts
test/suite/services.test.ts

- Insights login flow support copy link

KXI-38049 Login flow copy link

---

package.json
src/classes/insightsConnection.ts
src/extension.ts

- Disable reset scratchpad while API is not work correctly

Disable reset

---

server/src/parser/literals.ts
syntaxes/q.tmLanguage.json

- Updated symbol literal regex

KXI-43704: Symbol Literal should account for forward slashes

---

README.md
package.json
server/src/linter/checks.ts
server/src/linter/index.ts
server/src/linter/rules.ts
server/src/parser/parser.ts
server/src/qLangServer.ts
server/src/server.ts
server/src/util/index.ts
src/commands/buildToolsCommand.ts
test/suite/parser.test.ts
test/suite/qLangServer.test.ts

- Refactored TS Linter to use new parser features.
- Supports both q and quke files
- Updated linter doc

[LS] Refactored Typescript Linter

---

src/webview/components/kdbDataSourceView.ts
test/fixtures/index.ts
test/fixtures/webview.ts

- Fixes dropdown selection glitch.

KXI-45386: Fix datasource dropdown fix

---

package-lock.json
package.json

- Set the engine to January 2024

KXI-44147 update vscode engine

---

src/commands/workspaceCommand.ts

- Show insights connections only for python workbooks

KXI-45462: Show only insights connections for python workbooks

---

src/services/connectionManagerService.ts
test/suite/services.test.ts

- fix active connection disconnect behaviour

smallfix for insights active connection

---

src/services/resultsPanelProvider.ts
test/suite/panels.test.ts

fix workbooks bug

---

CHANGELOG.md

- Draft change log for release 1.5

VSCode 1.5 CHANGELOG.md

---

src/commands/dataSourceCommand.ts

- Add check of undefined `res`

KXI-46574: Regression: Datasource double error message

---

src/utils/core.ts

add more txt to connect dialog

---

src/commands/serverCommand.ts

improve the code

---

src/commands/workspaceCommand.ts
src/services/dataSourceEditorProvider.ts

- Force refreshing connection explorer.

KXI-46944: KX Tab Never visited but a datasource is opened

---

src/services/dataSourceEditorProvider.ts
src/webview/components/kdbDataSourceView.ts
test/suite/webview.test.ts

- Use input event 
- Added debounce for input

KXI-46934: Datasource editor new input on text fields disappear on Ctrl+S

---

CHANGELOG.md

md-change-log-1.5-edits

---

src/utils/dataSource.ts

KXI-46528 Fix on Windows

---

CHANGELOG.md

Release notes mdoody

---

CHANGELOG.md
README.md

mdoody-images-fixes

---

server/src/linter/checks.ts
server/src/parser/language.ts
server/src/parser/lexer.ts
server/src/parser/parser.ts
server/src/parser/tokens.ts
server/src/parser/utils.ts
syntaxes/q.tmLanguage.json
test/suite/parser.test.ts

- Fixed reported false positives

KXI-47774: Linter Fixes

---

src/classes/localConnection.ts
src/extension.ts
src/services/connectionManagerService.ts
src/utils/executionConsole.ts
test/runTest.ts

- fix issues with local conn disconnection

fix local conn issues

---

src/classes/localConnection.ts
src/extension.ts
src/services/connectionManagerService.ts
src/utils/executionConsole.ts
test/runTest.ts

- fix issue related to disconnection from local conn
- fix issue of not showing q console output when run queries and results tab is not visible.

[KXI-47953]local conn main fix

---

src/extension.ts

- Run command disconnect on stop q command.

KXI-47671: Disconnect bundled KDB+ connection on stop q

---

package-lock.json

fixes lock file

---

src/classes/localConnection.ts

- Refreshes completion list after script execution on KDB+ conections

KXI-47672: Refresh completion list

---

package.json
server/src/qLangServer.ts
src/commands/clientCommands.ts
src/commands/requestCommands.ts
src/extension.ts
test/suite/commands.test.ts
test/suite/qLangServer.test.ts

- Added hotkey to cache function parameters

KXI-36324: Hotkey to cache function parameters

---

src/classes/insightsConnection.ts
src/extensionVariables.ts
src/models/config.ts
src/services/connectionManagerService.ts

- make vscode extension insights version aware

make vscode extension insights version aware

---

CHANGELOG.md
src/ipc/QGuid.ts

- guid types are correctly detected and displayed for insights

Fix for detecting guid type for insights

---

package.json

- remove connect option from meta

Bugfixes to meta nodes

---

src/classes/insightsConnection.ts

- add logs for populate scratchpad
- disable scratchpad url change for 1.11 while is not merged

add logs for populate scratchpad

---

CHANGELOG.md
src/classes/insightsConnection.ts
src/classes/localConnection.ts
src/commands/dataSourceCommand.ts
src/commands/serverCommand.ts
src/extensionVariables.ts
src/services/resultsPanelProvider.ts
src/utils/queryUtils.ts
test/suite/commands.test.ts
test/suite/utils.test.ts

-  fix bug when close results tab

fix bug when close results tab

---

.snyk

add snyk check

---

.snyk
CHANGELOG.md
package-lock.json
package.json

fix snyk vulnerability 

---

.snyk
CHANGELOG.md
package-lock.json
package.json

- fix ag-grid issue
Cherry-pick from dev branch

Fix snyk vulnerability in  main

---

CHANGELOG.md

- Changed wording, whitespaces, and spelling of 1.6 changelog

Correct formatting and spellings for 1.6 changelog

---

src/classes/insightsConnection.ts
src/commands/serverCommand.ts
src/models/insights.ts
src/services/kdbInsights/codeFlowLogin.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/services.test.ts
test/suite/webview.test.ts

- Accept self-signed ssl certificates
- Add https for Insights url if scheme is not specified

Accept self-signed ssl certificates and add https for Insights

---

package-lock.json
package.json
src/commands/serverCommand.ts
src/extension.ts
src/models/messages.ts
src/models/server.ts
src/panels/newConnection.ts
src/validators/kdbValidator.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/commands.test.ts
test/suite/panels.test.ts
test/suite/webview.test.ts

KXI-50032 - edit connection

---

.github/workflows/app-sec-template.yml
.github/workflows/main.yml
.github/workflows/prod_release.yml
.github/workflows/release.yml

KXI-51959: Add run on feature/* branches plus update versions of actions

---

package.json
src/extension.ts

- Fixes deleting a datasource does not close the open editor
- Fixes toggle parameter cache doesn't work in workbooks
- Fixes extension walkthrough "Ignore/hide this help" button does not work

Several Fixes

---

src/commands/serverCommand.ts
src/services/connectionManagerService.ts
src/utils/connLabel.ts
src/utils/core.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/commands.test.ts

- add changes requested to edit connections
- improve code and logic quality

KXI-50032 Edit connection

---

package.json
src/extension.ts
src/utils/workspace.ts
test/suite/workspace.test.ts

- Fix for files cannot be executed from entity tree

Fix for files cannot be executed from entity tree

---

src/extension.ts
src/utils/core.ts
test/suite/commands.test.ts

- fix unnamed alias for all connections, this function should be removed on 1.9

Fix unnamed alias

---

.snyk
src/webview/components/kdbNewConnectionView.ts

- Fix edit local conn bug
- add ignore to snyk to work with PRs while fixing it.

Fix edit local conn bug found

---

src/webview/components/kdbNewConnectionView.ts

fix edit conn auth

---

src/webview/components/kdbNewConnectionView.ts
test/suite/webview.test.ts

- add dialog to edit connection form

fix create label dialog for edit conn

---

package.json

Update extension description

---

.snyk
package-lock.json
package.json

KXI-52471 solve axios vulnerability

---

src/services/kdbTreeProvider.ts

- Expands label after adding or editing a connection

Labels collapsible state

---

src/services/connectionManagerService.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/webview.test.ts

- Fix issues founded in the tests

KXI-52704 - label issues

---

src/commands/installTools.ts
src/utils/core.ts

- Gracefully handle start q process failures

Fix for start q process issue

---

package.json

Fix datasource icon

---

CHANGELOG.md
package.json

Update main for the remaining PRs

---

CHANGELOG.md
README.md

editorial changes

---

src/commands/serverCommand.ts
src/extensionVariables.ts
src/models/connectionsModels.ts
src/services/connectionManagerService.ts
test/suite/commands.test.ts
test/suite/services.test.ts

[KXI-52687] add tests and auth data

---

src/commands/serverCommand.ts
src/extension.ts
src/services/connectionManagerService.ts
test/suite/commands.test.ts
test/suite/services.test.ts

KXI-52817 Add import connections

---

src/classes/insightsConnection.ts
src/extension.ts
src/services/connectionManagerService.ts
test/suite/services.test.ts

- add changes for future reset scratchpad (this doesn't affect nothing now, just preparing)

add changes for future reset scratchpad

---

server/src/qLangServer.ts

- Fixed the recursive display of references.

Fixed show call hierarchy recursive display

---

src/commands/serverCommand.ts
test/suite/commands.test.ts

- Added dialog to import for conflicting names

Added import option to overwrite connections

---

README.md

- cleaned up the Import/Export Connection config 
- added the new Row Limit property in the Data Sources section as a row to the table under that section (Jira ticket: https://kxl.atlassian.net/browse/KXI-52588)

Import/Export and Add Limit

---

CHANGELOG.md

- Draft CHANGELOG for release 1.8

Version-1.8-CHANGELOG

---

CHANGELOG.md
server/src/qLangServer.ts
test/suite/qLangServer.test.ts

- Fixed windows bug
- Added multiple labels to change log

[LS] Fix multiple files windows bug

---

src/classes/insightsConnection.ts
src/utils/connLabel.ts
src/utils/core.ts
src/webview/components/kdbDataSourceView.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/utils.test.ts
test/suite/webview.test.ts

- fix errors found in e2e tests

fix errors found in e2e tests

---

CHANGELOG.md
package.json
src/services/resultsPanelProvider.ts
test/suite/panels.test.ts

- Fix for results tab flickering , improving of UX
- Fix for Issue  #382

Improve results tab

---

package-lock.json
src/classes/insightsConnection.ts

- ping insights when connect to it.

KXI-38329 - ping for a scratchpad when connecting to insights

---

src/services/kdbTreeProvider.ts
test/suite/commands.test.ts

- add version to insights connection tooltip

[KXI-54016] - Display version of Insights user is connected to 

---

src/models/connectionsModels.ts
src/models/messages.ts
src/panels/newConnection.ts
src/webview/components/kdbNewConnectionView.ts
src/webview/components/styles.ts
src/webview/styles/style.css

- move new connections webview from vscode ui to sl

migrate from vscode ui to sl

---

server/src/qLangServer.ts
test/suite/qLangServer.test.ts

- Implemented semantic highlighting for locals
- Fixed completion error for new files

[LS] Semantic highlighting for locals

---

src/webview/components/kdbNewConnectionView.ts

- fix issue with new conenctions

KXI- 55598 fix issue with new connections

---

src/webview/components/kdbNewConnectionView.ts

fix labels issues

---

src/services/resultsPanelProvider.ts

fix ds and wb

---

src/webview/components/kdbNewConnectionView.ts

improve labels

---

package-lock.json
package.json

- Downgraded shoelace due to issues with dropdown component.

Downgraded shoelace to 2.17.1

---

src/classes/insightsConnection.ts
src/services/connectionManagerService.ts
src/services/resultsPanelProvider.ts
src/utils/core.ts

- Hotfix for version validation

fix version validation

---

CHANGELOG.md
package-lock.json
package.json
src/classes/insightsConnection.ts
src/services/connectionManagerService.ts
src/services/resultsPanelProvider.ts
src/utils/core.ts
test/suite/panels.test.ts

Main 1.9.1 to dev

---

src/ipc/QChar.ts

fix ipc qchar

---

src/classes/insightsConnection.ts
src/commands/serverCommand.ts
src/models/scratchpadResult.ts
src/utils/queryUtils.ts
test/suite/utils.test.ts

- Add `formatScratchpadStacktrace` util function
- Updated `writeScratchpadResult` to append output from new function

KXI-52672 Show stack trace on errors against Insights scratchpad

---

package.json
resources/evaluatePy.q
src/classes/localConnection.ts
src/extension.ts
src/services/connectionManagerService.ts
src/utils/queryUtils.ts
test/q/evaluatePy.quke

- evaluatePy.q
- update Python checks to include local connections

KXI-37307 Add support for Python in non-scratchpad processes

---

src/utils/core.ts
src/utils/cpUtils.ts

- Fixed the bug not starting bundled q server on WSL
- Minor regex and case fix

Fix for WSL spawn bug

---

package-lock.json
package.json
src/commands/dataSourceCommand.ts

- Made the log message silent
- Upgraded Shoelace to latest

Fix for double error message with data sources

---

src/webview/components/kdbNewConnectionView.ts

- Use a key value without space
- Button group for add/remove label

Fixed issue with labels using space

---

src/services/resultsPanelProvider.ts

- Unicode chars in q strings are displayed correctly

Fix for unicode chars for structuredText

---

src/services/dataSourceEditorProvider.ts

- Added notification for data source refresh

Data source refresh notification

---

resources/evaluate.q
src/classes/localConnection.ts
src/services/resultsPanelProvider.ts
test/suite/panels.test.ts

- Added client support for structuredText for kdb+ connections

Client support for structuredText for kdb+ connections

---

src/webview/components/kdbDataSourceView.ts

- Fixed a bug where an underscore is added to QSQL target combo box.

Fixed qsql target added underscore

---

README.md

Updated the Grammar of Graphics section to add more details.

Update gg docs

---

.vscode/launch.json
src/classes/localConnection.ts
src/commands/serverCommand.ts
src/services/resultsPanelProvider.ts
src/webview/styles/resultsPanel.css
test/suite/commands.test.ts
test/suite/panels.test.ts

- Fix the UX for loading huge and complex data for the table
- Add loading overlay for results tab
- Fix issues for structuredText with only one column as result
- Fix issues with Error handling
- Improve code quality
- Add launch change to reduce the noise from other extensions while debugging

[KXI-33288] Fix UX for huge data and other fixes

---

resources/evaluate.q
resources/evaluatePy.q

- Updated q and Python wrapper functions

Updated q and Python wrapper functions

---

resources/evaluate.q
resources/evaluatePy.q

- Added more checks for png detection including magic number check for PNG

Improved gg plot png detection

---

resources/evaluate.q
resources/evaluatePy.q

- Removed a check from wrapper.

Remove a check from wrapper

---

resources/evaluate.q

Reverts KxSystems/kx-vscode#499
Accidentally merged in thinking it was KXI-58784
Call at 10:30 discussing this ticket with Ben J

Revert "KXI-58865 - [structuredText] char result renders incorrectly"

---

CHANGELOG.md
README.md

- Added PyKX note about GG Plot.
- Updated change log.

Version 1.10 Docs

---

resources/evaluate.q
src/commands/serverCommand.ts
src/services/resultsPanelProvider.ts

fix abnormal count of rows

---

sonar-project.properties

- workaround twhile have sonar issues

workaround for sonar

---

README.md
resources/evaluate.q
resources/evaluatePy.q
src/classes/localConnection.ts
src/commands/serverCommand.ts
src/models/queryResult.ts
src/utils/queryUtils.ts
test/suite/utils.test.ts

- Added `.qp.display2` function to display a gg plot in vscode.
- Moved png detection to extension.

[ggplot] Move png detection to extension

---

sonar-project.properties

remove timeout

---

src/commands/dataSourceCommand.ts
src/commands/workspaceCommand.ts
src/utils/core.ts
src/webview/components/kdbDataSourceView.ts
test/suite/commands.test.ts
test/suite/utils.test.ts

Rename conn connections

---

CHANGELOG.md
package-lock.json
package.json

- Fix third-party package vulnerability

fix esbuild package

---

src/services/resultsPanelProvider.ts

- fix issues with new insights version

fix changes at insights at results tab

---

src/classes/localConnection.ts
src/extension.ts
src/extensionVariables.ts
src/models/customAuth.ts

- Added async
- Removed non type safe code

Added async to custom auth api

---

README.md

- Update readme file to add customized authentication

add custom auth logic to readme file

---

src/classes/localConnection.ts

- Adapt https://github.com/KxSystems/kx-vscode/pull/526

Adapt PyKX wrapper changes

---

src/webview/components/kdbDataSourceView.ts
src/webview/components/styles.ts

- Removed +Add Parameter button caret
- Made container width 80% (3 columns) by default
- Made date field 1 column
- Adjust menu-item hover and focus colors to follow vs code theme
- Refactored menu border color to use css variables

Refactor UDA UI changes

---

src/classes/insightsConnection.ts
src/commands/dataSourceCommand.ts
test/suite/commands.test.ts

- add error workaround while backend doesn't solve these issues

add error workarounds

---

src/commands/dataSourceCommand.ts
src/extensionVariables.ts
src/webview/components/kdbDataSourceView.ts
test/suite/commands.test.ts
test/suite/index.ts

add new required meaning

---

src/classes/insightsConnection.ts
src/commands/dataSourceCommand.ts
src/utils/uda.ts
test/suite/commands.test.ts

add populate UDA

---

src/commands/dataSourceCommand.ts
src/utils/uda.ts
test/suite/commands.test.ts

add error log for uda run

---

CHANGELOG.md

Version 1.11 CHANGELOG

---

README.md

fix images for UDA queries section

---

CHANGELOG.md
README.md
package-lock.json
package.json

V.1.11.1 dev to main

---

CHANGELOG.md
package-lock.json
package.json

Upodatedev to 1.12

---

src/extensionVariables.ts
src/utils/telemetryClient.ts

- make vscode RC(release-candidate) aware

make vscode rc version aware

---

resources/evaluatePy.q

-Added changes from KXI-62426 to this repo

KXI-62484 Add changes from KXI-62426 are in vscode extension evaluate.py.q

---

src/services/resultsPanelProvider.ts
test/suite/panels.test.ts

- fix issue with theme color for ag-grid

[KXI-62048]fix issue with theme color for ag-grid

---

src/utils/feedbackSurveyUtils.ts
test/suite/utils.test.ts

- Fix AC changed after delivery

[KXI-56283] Fix AC changed after delivery

---

CHANGELOG.md
package.json
src/commands/serverCommand.ts
src/extension.ts
src/extensionVariables.ts
src/services/queryHistoryProvider.ts
test/suite/commands.test.ts

- add copy query from query history

[KXI-38123] - Query History - Cannot inspect or copy contents

---

src/commands/serverCommand.ts
src/webview/components/kdbNewConnectionView.ts

- Remove the required from password

[KXI-63281] remove required for password

---

src/commands/serverCommand.ts
src/utils/dataSource.ts
src/webview/components/custom-fields/date-time-nano-picker.ts
src/webview/components/kdbNewConnectionView.ts
src/webview/components/styles.ts
test/suite/webview.test.ts

- small fixes removing console.log and adding new styles

Small fixes 2

---

src/extension.ts

- remove initialise of results tab

[KXI-64893] Do not change the selected tab on startup

---

src/services/notebookController.ts
src/services/notebookSerializer.ts

- Fixed notebook warning on execution end.
- Fixed notebook IE active connection detection
- Harden serialize in case of empty string in cell metadata

[fix] Fix for notebook warnings

---

README.md
src/commands/serverCommand.ts
src/panels/newConnection.ts
src/services/kdbTreeProvider.ts
src/utils/connLabel.ts
test/suite/commands.test.ts
test/suite/utils.test.ts

- [KXI-64600] remove email from docs
- [KXI-64930] add confirmation for connection removal
- [KXI-64977] Opening "Edit Connection" on multiple connections groups them in a label

Several tickets

---

package-lock.json
package.json

- Added proper scopes for settings.

Added scope for all settings

---

CHANGELOG.md
README.md

- Notebook showcase documentation.
- Changes for LS bug fixes.

Notebook showcase documentation

---

package-lock.json
package.json
server/src/parser/language.ts
server/src/parser/lexer.ts
server/src/parser/tokens.ts
server/src/qLangServer.ts
server/src/server.ts
src/commands/workspaceCommand.ts
src/extension.ts
src/utils/notifications.ts
syntaxes/q.tmLanguage.json
test/suite/commands.test.ts
test/suite/qLangServer.test.ts

- Fixed keywords after underscore operator is not identified as keyword.
- Line comments on system commands syntax highlighting is wrong.
- Fixed working without a workspace.
- Related files are determined using connection association.

[LS] Connection grouping for related files

---

src/commands/serverCommand.ts
src/commands/workspaceCommand.ts
src/panels/newConnection.ts
src/services/connectionManagerService.ts
src/services/dataSourceEditorProvider.ts
src/services/kdbInsights/codeFlowLogin.ts
src/services/kdbTreeProvider.ts
src/services/resultsPanelProvider.ts
src/utils/core.ts
src/utils/dataSource.ts
src/utils/feedbackSurveyUtils.ts
src/webview/components/custom-fields/date-time-nano-picker.ts
src/webview/components/kdbDataSourceView.ts
src/webview/components/kdbNewConnectionView.ts

Update coverage ignore comments

---

src/classes/insightsConnection.ts

fix for daps

---

src/extension.ts

- Expanding nodes within My Q Connection errors and says not connected.

Fix for KXI-65258

---

src/utils/connLabel.ts
test/suite/utils.test.ts

labels fixes

---

README.md
package.json

- Added missing settings to README

Add missing settings to docs

---

CHANGELOG.md
package-lock.json
package.json
src/utils/core.ts
src/utils/cpUtils.ts
test/suite/utils.test.ts

- Fixed issue with corrupted settings for VSCode

fix for corrupted settings

---

.vscode/launch.json
package-lock.json
package.json
src/classes/replConnection.ts
src/commands/workspaceCommand.ts
src/extension.ts
src/services/notebookController.ts
test/suite/classes/repl.test.ts
test/suite/commands/workspaceCommand.test.ts

[REPL] Python select interpreter support (venv)

---

package-lock.json
package.json
src/classes/replConnection.ts
src/extension.ts
src/utils/core.ts
src/utils/registration.ts
src/utils/shell.ts
test/suite/classes/repl.test.ts
test/suite/utils/core.test.ts

- Fixed .env on win32
- Fixed local q on remote

Fix for .env on win32 and local q on remote

---

CHANGELOG.md
README.md

Docs - release 1.14

---

CHANGELOG.md
README.md

1.14 docs updates

---

.github/workflows/prod_release.yml

Add publishing to openvsx
