KxSystems/kx-vscode

package.json
src/extension.ts

- Added context menu item `Execute Entire File` for `.q` and `.py` files.

KXI-35472: Add Execute Entire File context menu item to explorer

---

.github/workflows/app-sec-template.yml
.github/workflows/prod_release.yml
.github/workflows/release.yml
package.json

KXI-33125: Enable publish to marketplace in prod release

---

src/panels/newConnection.ts
src/validators/kdbValidator.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/validators.test.ts
test/suite/webview.test.ts

- fixing labels and validators errors

KXI-38118 - Minor connection page issues

---

package.json
src/commands/serverCommand.ts
src/services/connectionManagerService.ts
src/services/dataSourceTreeProvider.ts
src/utils/dataSource.ts

- fix small bugs from multiple connections and datasources

Small bugs

---

src/classes/insightsConnection.ts
src/extensionVariables.ts
src/services/connectionManagerService.ts
test/suite/services.test.ts

- Ping Insights and drop connection

Ping insights

---

src/extension.ts

- add commands to clear context when the extension is activated

KXI-45510 Clear connections context when the extension is activated

---

src/classes/insightsConnection.ts
src/services/connectionManagerService.ts

- add error output for connection drop

KXI-45655 - Connections Randomly Dropping

---

package-lock.json
package.json
src/extensionVariables.ts
src/services/connectionManagerService.ts
src/utils/core.ts
test/suite/utils.test.ts

- added options to disable/enable conn hydrate and network watcher
- update axios
-

KXI-45990 Add option to disable hydrate from insights

---

package.json
src/extension.ts
src/services/workspaceTreeProvider.ts

- When adding workbook or data source they are placed in `.kx` folder in workspace and saved.
- If no workspace is opened, the add commands are disabled.

KXI-46005: Workbook and datasource files should be put into a dedicated folder

---

src/commands/serverCommand.ts
src/services/connectionManagerService.ts

- Updating `ext.connectionNode` on activate

KXI-46214: Tree does not re-appear when active connection changes

---

src/utils/dataSource.ts

- Imports old style datasources into workspace `.kx` folder
Question:
- Should we import into a dedicated forder under `.kx` using original data source file name(.kdb.json) ? This way user can easily find them.

KXI-46528: Regression: Import old style data sources into .kx folder

---

package-lock.json
package.json
src/commands/dataSourceCommand.ts
src/commands/serverCommand.ts
src/commands/workspaceCommand.ts
src/extension.ts
src/services/connectionManagerService.ts
src/services/dataSourceEditorProvider.ts
src/utils/core.ts
test/suite/commands.test.ts
test/suite/services.test.ts

- Add confirm dialog offering to connect to a not connected connection
- add the dialog to workbooks
- add the dialog for actions in DS

[KXI-46633] Add confirm dialog to connect

---

src/commands/workspaceCommand.ts

- Get label for local server before sending to runQuery

KXI-46862: Workbook execution on local KDB+ connections is broken

---

src/classes/insightsConnection.ts
src/commands/serverCommand.ts
src/models/insights.ts
src/services/kdbInsights/codeFlowLogin.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/services.test.ts
test/suite/webview.test.ts

- Add optional realm field to insights connection, existing connections will not be effected.

KXI-46026: Support Insights Enterprise Trial (add realm field)

---

package.json
src/commands/serverCommand.ts
src/extension.ts
src/services/kdbTreeProvider.ts
test/suite/commands.test.ts

- add command to refresh all
- add command to refresh only specific node

[KXI-47787] Get Meta refresh

---

package.json
src/classes/insightsConnection.ts
src/commands/serverCommand.ts
src/extension.ts
src/models/meta.ts
src/services/connectionManagerService.ts
src/services/kdbTreeProvider.ts
src/services/metaContentProvider.ts
test/suite/commands.test.ts
test/suite/services.test.ts

- open meta object json when click on it

open meta json from node tree

---

src/classes/insightsConnection.ts

- make vscode extension choose the correct scratchpad endpoint accordingly with Insights version

[KXI-42655] VSCode Handle changes to the scratchpad as part of 1.11

---

src/classes/localConnection.ts
src/commands/installTools.ts
src/commands/serverCommand.ts
src/extension.ts
src/services/connectionManagerService.ts
src/utils/core.ts
src/validators/kdbValidator.ts
test/suite/commands.test.ts

- 500 ms interval when executing query on KDB+ connections reduced to 50 ms
- Connection names are not case sensitive any more
- Same address can be used under different connection names
- Add authentication implemented for KDB+ connections which asks for credentials
- Connection settings in settings.json is now manually editable
- Changes are backwards compatible, user's current settings work as is

Fixes several connection related issues

---

CHANGELOG.md
README.md
server/src/qLangServer.ts
src/extension.ts
test/suite/qLangServer.test.ts

- onSelectionRanges capability on LS is implemented so Expand Selection standart command works on q source
- LS features now work on newly created q and quke files
- Updated README for double click selection setting
- Updated CHANGELOG

Implement expand selection command

---

CHANGELOG.md
src/classes/insightsConnection.ts

- Convert timestamp to UTC for populate scratchpad

Convert ts to utc for populate sp

---

src/commands/serverCommand.ts
src/services/connectionManagerService.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/commands.test.ts
test/suite/webview.test.ts

KXI-50022 - fix some bugs related to conenctions

---

src/services/kdbTreeProvider.ts
src/utils/connLabel.ts
test/suite/utils.test.ts

- Fix Error: Labels are collapsable without any connection under it
Now the labels without any connection under it are not expandable/collapsable

fix labels collapse at conn tree

---

src/commands/serverCommand.ts

- Remove labels when remove conn

Remove labels when remove conn

---

src/commands/serverCommand.ts
src/extensionVariables.ts
src/panels/newConnection.ts
src/services/kdbTreeProvider.ts
src/utils/connLabel.ts
src/webview/components/kdbNewConnectionView.ts
test/suite/panels.test.ts
test/suite/utils.test.ts
test/suite/webview.test.ts

- Move the Create Connection button from the upper right to the lower left on for all connection types.
- When I create a new label, that label should then populate the dropdown after I click Save on the Add New Label modal.
- Primary button name should be Update Connection, not Edit Connection and the button should be moved from the upper right to the lower left of the screen.
- If I add a new label, the label gets added to the connection window when I click save from the modal window. This creates an issue if I decide to choose a different label before I save the edit as the label is already shown in the connection window. Can we add the label after the edit connection is saved and not when creating a new label?
- Can we do validation on the Create button as clicking this before I set …

Larry change requests

---

package.json
src/commands/serverCommand.ts
src/extension.ts
src/utils/core.ts
test/suite/utils.test.ts

- allow user to disable install kdb popup
- will no longer change to results tab when user connect to an connection

[KXI-30428] allow user to disable install kdb popup

---

src/commands/serverCommand.ts
src/extension.ts
src/services/resultsPanelProvider.ts
src/webview/styles/resultsPanel.css
test/suite/commands.test.ts
test/suite/panels.test.ts

- Fix issues with large results
- Entire refactor to Results Tab grid
- solve issues from KXI-30984 (save column width, in case same type of results are executed)

Fix issues with large results

---

server/src/qLangServer.ts
src/extension.ts
test/suite/qLangServer.test.ts
test/suite/utils.test.ts

- Implemented multi file language server features

Multi file language server features

---

package.json
server/src/qLangServer.ts
server/src/server.ts
src/extension.ts
test/suite/qLangServer.test.ts
test/suite/utils.test.ts

- Add scope setting
- Incrementally parse the files in the workspace

Implement LS features for all the files in the workspace

---

CHANGELOG.md
src/extension.ts

- Use contents of the current file for REPL
- Update CHANGELOG

Fix for run q file not using the current editor contents

---

package.json
src/extension.ts
src/utils/core.ts
test/suite/utils.test.ts

- Always enable datasource and workbook add commands
- Show option to open a workspace folder in case of no workspace

Add warning to datasource and workbook add commands

---

CHANGELOG.md
server/src/parser/parser.ts
server/src/parser/utils.ts
server/src/qLangServer.ts
src/extension.ts
src/utils/core.ts
test/suite/qLangServer.test.ts
test/suite/utils.test.ts

- Added more tests
- Parser fixes
- Removed unused function
- Fixed datasource and workbook no workspace warning text
- Update change log

[LS] More coverage and fixes

---

src/classes/localConnection.ts
src/webview/components/kdbNewConnectionView.ts

- fixed error with bundle q
- fixed errors with labels

V.1.9.0 dev to main

---

server/src/parser/parser.ts
server/src/parser/utils.ts
server/src/qLangServer.ts
test/suite/qLangServer.test.ts

- Implemented semantic highlighting for lambda definitions

[LS] Semantic highlighting for lambda definitions

---

sonar-project.properties
src/services/completionProvider.ts
src/services/dataSourceEditorProvider.ts

- Added completions for https://code.kx.com/insights/1.12/enterprise/analysis/queryapi.html
- Removed a double error message

Added api completions

---

package.json
resources/dark/plot.svg
resources/evaluate.q
resources/light/plot.svg
src/classes/localConnection.ts
src/commands/serverCommand.ts
src/extension.ts
src/models/plot.ts
src/models/queryResult.ts
src/services/chartEditorProvider.ts
src/services/workspaceTreeProvider.ts
src/utils/workspace.ts
src/webview/components/kdbChartView.ts
src/webview/components/styles.ts
src/webview/main.ts
test/suite/services.test.ts
test/suite/webview.test.ts
test/suite/workspace.test.ts

- Implemented gg plot first phase

gg plot first phase

---

src/classes/insightsConnection.ts
src/commands/dataSourceCommand.ts
src/commands/serverCommand.ts

- Unified KDB+ and Insights connection query progress, now both displays the same notification in the status bar
- When clicked becomes a cancellable notification. Cancellation discards the results and does not display results (or plot).

Unified query progress for KDB+ and Insights

---

README.md

- Update the "kdb process executing q and Python code" section to add the prerequisite for executing Python code against kdb+ connections (Jira ticket: [Add support for Python in non-scratchpad processes](https://kxl.atlassian.net/browse/KXI-37307))
-

Update docs: Python code against kdb+ connections

---

resources/evaluatePy.q
src/classes/localConnection.ts
src/commands/serverCommand.ts
src/extension.ts
src/services/resultsPanelProvider.ts

- Added gg plot support for PyKX on kdb+ connections
- Fixed a regression when PyKX do not display on KDB results tab.

gg plot support for pykx

---

src/classes/insightsConnection.ts
src/services/resultsPanelProvider.ts

- Use serialized (old) code path for Python queries on Insights scratchpad for KDB Results view

Workaround for Python structuredText bug

---

resources/evaluate.q

- fix char type wrapper bug for local q

KXI-58865 - [structuredText] char result renders incorrectly

---

resources/test/vscode-common.quke

Added test file which contains scratchpad evaluate and structText unit tests. The code is not ready to go and will need refactoring in order to work with the vscode project. 
-

KXI-58784 Adding unit tests for evlauate.q in vscode extension

---

resources/evaluate.q

q bug with iasc that fails for (symbol; long), so we need to handle this error Also fixes a different q bug - a side effect of iasc that applies a `s attribute if the data is sorted, so we cache the data attributes before applying iasc to the data
-

KXI-59061 Handle errors from iasc when building structuredText output

---

resources/evaluate.q

- Added additions under the request from Philip to make api easier to use
- Removed values changing to values if items are singular
- enlisted all incoming values
- changes are related to https://kxl.atlassian.net/browse/KXI-59012

KXI-59012 Make structuredText results easier for consumers to use 

---

resources/evaluate.q
src/models/queryResult.ts
src/services/resultsPanelProvider.ts
src/utils/queryUtils.ts
test/suite/utils.test.ts

- Refactoring for structuredText API changes
- Always use "text" for table columns

[structuredText] Refactor for API changes

---

src/utils/queryUtils.ts
test/suite/utils.test.ts

- q server running on windows append an invisible “\r” on bytes like “0x89\r” which is handled with this.
- test case is added

[Bug] Fixed png detection from a windows q server

---

src/utils/queryUtils.ts
test/suite/utils.test.ts

[backport] fixed png detection from a windows q server

---

src/commands/dataSourceCommand.ts
src/commands/workspaceCommand.ts
src/utils/core.ts
src/webview/components/kdbDataSourceView.ts
test/suite/commands.test.ts
test/suite/utils.test.ts

- fix issues with renaming connections for existing workbooks and ds

fix issues with renaming connection

---

src/classes/localConnection.ts
src/extension.ts
src/extensionVariables.ts
src/models/customAuth.ts

- Implemented custom authentication for kdb+ connections.

Custom authentication for kdb+ connections

---

CHANGELOG.md
src/utils/execution.ts

- fix issue with large data csv convertion

Main 1.10.2 to dev

---

CHANGELOG.md
package.json
src/classes/insightsConnection.ts
src/commands/serverCommand.ts
src/commands/workspaceCommand.ts
src/extension.ts
src/services/connectionManagerService.ts
test/suite/commands.test.ts
test/suite/services.test.ts

- add reset scratchpad feature

[KXI-60351] Reset scratchpad

---

resources/evaluatePy.q

- Added support for toStructuredText format in vscode evaluate function. 
- Tested using local q tests found in scratchpad EDI.quke
- evaluate function parameters changed, will need different params to work. Not backwards compatible
- added the option for text, serialized, and structuredText

KX-58552 KXI-58552 Add structuredText to VSCode extension for Python

---

src/classes/localConnection.ts
src/models/customAuth.ts
src/services/connectionManagerService.ts
test/suite/classes.test.ts
test/suite/commands.test.ts
test/suite/services.test.ts
test/suite/utils.test.ts

- Pass connection labels to custom auth
- Renamed connection label to name
- Auth sample extension changes https://github.com/KxSystems/kx-vscode-auth/commit/f52a0cf2fe30cbdc9e8f43a686c54871a136f794

Pass connection labels to custom auth

---

.github/workflows/dev.yml
.github/workflows/prod_release.yml
.github/workflows/release.yml
README.md

This change will avoid the failing status of workflows appearing on the marketplace
-

Change naming convention for workflows and split out dev workflow

---

resources/evaluatePy.q

Summary
- Sampling from sets is now no longer deprecated and uses a explicit case to handle sampling functions
Changes
- Fixed a bug where sampling from a set or frozen set would not work in later versions of python.
Testing
- Updated unit test in scratchpad for doing samples on sets and frozen sets

KXI-61984 Scratchpad gets deprecation warning for using deprecated sampling set function 

---

package.json
src/classes/insightsConnection.ts
src/commands/dataSourceCommand.ts
src/commands/serverCommand.ts
src/services/notebookController.ts
src/services/notebookProviders.ts
src/utils/queryUtils.ts
test/suite/commands.test.ts
test/suite/notebooks.test.ts
test/suite/utils.test.ts

- Python execution support for `.py` files in DAP.
- Python populate scratchpad support for `.py` files in DAP.
- Support added for Python blocks in KX Notebooks as well.

Python execution support in DAP
